name: dilithium
description: #TODO: Add a description to the package.
version: 1.0.0
# repository: https://github.com/my_org/my_repo #TODO: Add repository

environment:
  sdk: ^3.4.1

dependencies:
  pointycastle: ^3.9.1
  cryptography: ^2.7.0
  binary: ^3.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
